- name: 'Set up Cloud SDK'
  uses: 'google-github-actions/setup-gcloud@v2'

- name: 'Deploy to Cloud Run'
  id: deploy
  uses: 'google-github-actions/deploy-cloudrun@v2'
  with:
    service: 'adgen-api'
    image: '${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/adgen-api:${{ github.sha }}'
    region: 'us-central1'
    flags: '--allow-unauthenticated --min-instances=0 --max-instances=3 --concurrency=80 --port=8080'
    env_vars: 'ENV=staging'

- name: Smoke test
  run: |
    set -e
    for i in {1..20}; do
      echo "Health attempt $i"
      curl -sf "${{ steps.deploy.outputs.url }}/health" && break || sleep 2
    done
    curl -sf "${{ steps.deploy.outputs.url }}/"
